### ISSUE TITLE
Getting an error while trying to use halite extension in berkshelf

### ISSUE THREAD

**Issue by dorongutman** [poise/halite#4]
I've installed the `halite` gem and added `extension 'halite'` to the top of the Berksfile file, but running `berks update` give the following error:
`/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.0.1/lib/berkshelf/berksfile.rb:89:inrescue in extension': Could not load an extension by the name halite'. Please make sure it is installed. (LoadError)`

**Comment by coderanger** [comment]
As I mentioned on the other ticket, you need to follow _all_ of the instructions. Either install halite with `chef gem install` (which I don't test or support) or learn to use Bundler. There is a really low chance that using a pre release of one of my cookbooks is a good idea.



On May 15, 2016 at 1:57:14 PM PDT, Doron Gutman <notifications@github.com> wrote:I've installed the halite  gem and added extension 'halite'  to the top of the Berksfile file, but running berks update  give the following error: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.0.1/lib/berkshelf/berksfile.rb:89:inrescue in extension': Could not load an extension by the name halite'. Please make sure it is installed. (LoadError)   —You are receiving this because you are subscribed to this thread.Reply to this email directly or view it on GitHub

**Comment by dorongutman** [comment]
I've tried both `gem install halite` and adding the gem to the Gemfile and running `bundle install`.
None of these worked.

And the reason I need to use a branch of one of your cookbooks is that there's a pull request pending without any resolution on it for the past month - https://github.com/poise/application_ruby/pull/83

**Comment by coderanger** [comment]
@dorongutman Make a subclass in your own cookbook rather than trying to run from a fork.

**Comment by dorongutman** [comment]
Can you explain that please ? How do I do that ?

On Tuesday, 17 May 2016, Noah Kantrowitz <notifications@github.com> wrote:

> @dorongutman <https://github.com/dorongutman> Make a subclass in your own
> cookbook rather than trying to run from a fork.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/poise/halite/issues/4#issuecomment-219562532>
>


-- 
Sent from a mobile thingy
Please excuse typos
